name: JDC-AX1800-PRO-IPQ60XX-6.12-NOWIFI

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * 6

jobs:
  build:
    uses: ./.github/workflows/build-openwrt.yml
    secrets: inherit
    with:
      repo_url: "https://github.com/LiBwrt/LibWrt.git"
      repo_branch: "25.12-nss"
      config_file: "configs/jdc-ax1800-pro-nowifi.config"
      diy_script: "libwrt.sh"
      firmware_tag: "JDC-AX1800-PRO-IPQ60XX-6.12-NOWIFI"
      firmware_description: "6.12 kernel firmware (Wired Only / No WIFI) + Wired NSS support"
      install_extra_packages: true
      kernel_version_file: "kernel-6.12"
