name: JDC-AX1800-PRO-IPQ60XX-6.12-WIFI

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  actions: read

jobs:
  build:
    uses: ./.github/workflows/build-openwrt.yml
    secrets: inherit
    permissions:
      contents: write
      actions: write
    with:
      repo_url: "https://github.com/LiBwrt/LibWrt.git"
      repo_branch: "25.12-nss"
      config_file: "configs/jdc-ax1800-pro-wifi.config"
      diy_script: "libwrt.sh"
      firmware_tag: "JDC-AX1800-PRO-IPQ60XX-6.12-WIFI"
      firmware_description: "6.12 kernel firmware with WIFI + Wired NSS support"
      install_extra_packages: false
      kernel_version_file: "kernel-6.12"
